name: Lint

on:
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 13.x
      uses: actions/setup-node@v1.4.0
      with:
        node-version: '13.x'

    - name: install packages and check syntax
      run: |
        yarn install --frozen-lockfile --silent
        yarn lint:ci
        yarn lint:css
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Slack notification FAIL
      uses: Ilshidur/action-slack@2.0.1
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: "Lint *FAILED* \n {{ GITHUB_ACTOR }} at {{ GITHUB_REPOSITORY }} \n Dude, your code sucks.."
